apiVersion: apps/v1
kind: Deployment
metadata:
  name: test123
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test123
  template:
    metadata:
      labels:
        app: test123
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ['sh', '-c', 'while true; do echo "Hello World"; sleep 10; done']
