# permissions for end users to edit sigadddeploymentoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: metrics-dep-operator
    app.kubernetes.io/managed-by: kustomize
  name: sigadddeploymentoperator-editor-role
rules:
- apiGroups:
  - cache.sig.com
  resources:
  - sigadddeploymentoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.sig.com
  resources:
  - sigadddeploymentoperators/status
  verbs:
  - get
