//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerId) DeepCopyInto(out *ContainerId) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerId.
func (in *ContainerId) DeepCopy() *ContainerId {
	if in == nil {
		return nil
	}
	out := new(ContainerId)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerMetrics) DeepCopyInto(out *ContainerMetrics) {
	*out = *in
	out.MaxCPU = in.MaxCPU
	out.MaxMemory = in.MaxMemory
	out.MemCpuRatio = in.MemCpuRatio
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerMetrics.
func (in *ContainerMetrics) DeepCopy() *ContainerMetrics {
	if in == nil {
		return nil
	}
	out := new(ContainerMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemCpuPair) DeepCopyInto(out *MemCpuPair) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemCpuPair.
func (in *MemCpuPair) DeepCopy() *MemCpuPair {
	if in == nil {
		return nil
	}
	out := new(MemCpuPair)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SigAddDeploymentOperator) DeepCopyInto(out *SigAddDeploymentOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SigAddDeploymentOperator.
func (in *SigAddDeploymentOperator) DeepCopy() *SigAddDeploymentOperator {
	if in == nil {
		return nil
	}
	out := new(SigAddDeploymentOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SigAddDeploymentOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SigAddDeploymentOperatorList) DeepCopyInto(out *SigAddDeploymentOperatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SigAddDeploymentOperator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SigAddDeploymentOperatorList.
func (in *SigAddDeploymentOperatorList) DeepCopy() *SigAddDeploymentOperatorList {
	if in == nil {
		return nil
	}
	out := new(SigAddDeploymentOperatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SigAddDeploymentOperatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SigAddDeploymentOperatorSpec) DeepCopyInto(out *SigAddDeploymentOperatorSpec) {
	*out = *in
	out.MemoryThreshold = in.MemoryThreshold.DeepCopy()
	out.CPUThreshold = in.CPUThreshold.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SigAddDeploymentOperatorSpec.
func (in *SigAddDeploymentOperatorSpec) DeepCopy() *SigAddDeploymentOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(SigAddDeploymentOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SigAddDeploymentOperatorStatus) DeepCopyInto(out *SigAddDeploymentOperatorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SigAddDeploymentOperatorStatus.
func (in *SigAddDeploymentOperatorStatus) DeepCopy() *SigAddDeploymentOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(SigAddDeploymentOperatorStatus)
	in.DeepCopyInto(out)
	return out
}
